apiVersion: apps/v1
kind: Deployment
metadata:
  name: sclab
  labels:
    app: sclab
    version: 1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sclab
  template:
    metadata:
      labels:
        app: sclab
        version: 1.0.0
    spec:
      containers:
      - name: sclab
        image: new-repo:version
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: sclab
spec:
  selector:
    app: sclab
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sclab
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /sclab
        backend:
          serviceName: sclab
          servicePort: 3000